### PR TITLE
Refactor denominator in pt_data_inventory

### PR DESCRIPTION
**Pull request by kylebaron**
Issue #221 

- missing means DV is `NA` and BQL is 0
- bql means BQL != 0 regardless of what is in DV
- obs means (1) not missing and (2) bql ==0

See further information in the confluence doc.

### CODE REVIEW

**Review by curtisKJ — APPROVED** [review]
Looks good.

**Comment by kylebaron** [comment]
Thanks for your review, @curtisKJ ; just checking that you reviewed the design doc in confluence and sign. off on that as well.  Just comment here on that too.

**Comment by curtisKJ** [comment]
@kylebaron, looked at that, too. I agree with Mike that having the footers match the descriptions in the documentation would be helpful. So instead of OBS: Observations, it's OBS: Observations (Non-BLQ).

**Comment by kylebaron** [comment]
Thanks; will you open an issue to and say what the change is?

**Comment by kylebaron** [comment]
Write it like a user story:

"As a user, I want the footer to say ...."  

You are asking for this and we'll do it.

**Comment by curtisKJ** [comment]
Issue created #228

**Pull request merged**
